site_name: SUAFT
site_description: Documentation for the Still Unnamed Air Filter Thing
site_author: Jon Harper
site_url: https://jon-harper.github.io/air_filter
repo_url: https://github.com/jon-harper/air_filter
repo_name: "GitHub: jon-harper/air_filter"
edit_uri: ""
copyright: Copyright &copy; 2023 Jonathan Harper

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - def_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append: 
        - include/links.md
        - include/abbrev.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.footer
    - navigation.expand
    - toc.follow
  icon:
    logo: material/air-filter
  font:
    text: Noto Sans
  palette: 
    - scheme: slate
      primary: light blue
      accent: orange
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to light mode
    - scheme: default
      primary: light blue
      accent: orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode

extra:
  social:
    - icon: simple/kofi
      link: https://ko-fi.com/jonspaceharper
      name: "Buy me a Ko-Fi!"
    - icon: material/home
      link: https://jon-harper.github.io/
      name: "jonspaceharper's Homepage"

extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search

nav:
  - SUAFT 120:
    - v3/index.md
    - v3/bom.md
    - v3/prep.md
    - v3/assembly.md
  # - V2:
  #   - v2/index.md
  #   - v2/single.md
  #   - v2/dual.md
  #   - Assembly:
  #     - v2/prep.md
  #     - v2/fans.md
  #     - v2/filter.md
  - SUAFT v1:
    - v1/index.md
    - v1/single.md
    - v1/dual.md
    - v1/inserts.md
    - v1/assembly.md